[gcp]
type = "service_account"
project_id = "qrng-database"
private_key_id = "1669bf950a2c8a57c350bcd31f94699eb02f5188"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuAIBADANBgkqhkiG9w0BAQEFAASCBKIwggSeAgEAAoIBAQCK/3iq3yURsAmI
xYlMKzhG1BA7V94HGIfrmILvo5HpLcJja4mwNrjtkYzUc9gtSj5b4s+eYpUcelA0
tYsfniILehzGtcVceBWYFKDR2TgMZj0vep5R+cPpzyLfLUso7Qp+pRXgt1o40GDn
VUB23OgYYwsiPSpAlKAlgznUeipFVvx6nC2a5D+HAGg2zw04Io021s1V/t53i1O2
l8ChteeilahrbRcT9yFyJn+ryW53PmqgStwzFFue0rxbUtRk3aGThGwYCyL/QBYf
b7HL3RYfCTihNXOW121EFOrDe1H2to8ADk8U7Ugcu12A6lQmN2dVmQACIUbcDmTA
34/vcW0XAgMBAAECgf8YKVBQY3mOGYuOusei9eBSb4pixmNR2HHIAjrAbS5v2gRw
Q8ErYFfE9AgG5hwtwzoTvtlYLsq8qIZIo0YLuPEyDYfzAqXL7RPT28IYuCmF/j+k
gSwEE+Z6PgdRxA3Mj2fDm+6xoS2NsqsliywpfTzbAFxvFzLBBxTPcIAc7x9p7fNW
CPb1jK1O3khP+ix1QgVj9ZUdbcSRkP4ZnG3jZ/Tx6dErrV1FzViW3tgM5HDMmrKq
yZW3tOPM4+8ryYZCxiXXMSrGqx7IFpvEUU1EfrE5eSAjpsLiIYz3YuTIEW12qZ68
mYxs/A0YuSaIlCIss+4GFrQsLga6tl0qjepBNlkCgYEAw4E//WqQJvFMmOII+d+t
8AGYKfGx5oeAvuC52oj0wXI6zsklbK7edqqf6+hwmm9hm4FA7wQ7QAVjR4tTA82u
c60GUpK9ZmgoXjemr8+OGmZHYBqGCsweHpP4XaPqeZ4deb7B2MDp4gjJesmhD63Y
dURn2UWgZ7ONgUHMLjQPvekCgYEAtgISjERhsdp5wsk2VeAKTrELBMMoP9zcNPTp
PGR9AacIzaUwdAgX+/FtEse9jeUWWoDrtoCWVRZimdo7GDlsG/uMb/8PDWq/LqvO
XYpr+nWl8cRfcTiljWiQaaQZtaW9/tK7AD+wHbNx5v3gwZMzMuuxR8AMq+fZhUYE
iDk18v8CgYAHlUXUIIQC3q0n6OyMNJ7chlNOnS9XT74wqSrMTS+hKTsatjabZpT+
aVPWpKdpdhSFIZhRLQrXSt408jSAG0Q+/GEYZtSt2jBmpyXx/8z1PS5bjevRE2W/
reGeUDNSEE34YOvH6oOn3sth1dxHbWjN859LkCXOn+pHLzQqPp61sQJ/Unid7vEN
U4mropeKB199TCrs0zubAVUScuyGwtbFzfniA0zWp70DISZERj47phAoENpZ9FhP
xj5eb1hzboaWdheFizoHmAzGlF9FIx2Vz+d/Sg2xMZx5Z5n51eSFwclYTh8unO4+
3zZwZjqjnRMWH/ysV9at5zcnWTxg0VkbGQKBgHC3Zvn3Zf0220Yv28ZM6J7M5l3A
Ey2x56ig/f47u5WvEEESFR/A8vKTQLIkVrzm+WjzM77ScwiiOZI+1reRlO7YcB4n
koe3cjn2qOGqpLnpDyAYe8nmZ2vVwgq7nk+dFTnm1V4pqZDitmf/ULnioRUDPN6j
KeBlsVjTilHxqLSd
-----END PRIVATE KEY-----
"""
client_email = "streamlit-logger@qrng-database.iam.gserviceaccount.com"
client_id = "118004251546286510098"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-logger%40qrng-database.iam.gserviceaccount.com"
universe_domain = "googleapis.com"